apiVersion: v1
kind: Service
metadata:
  name: phplb
  labels:
    app: phpapp
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: phpapp
  ports:
  - nodePort:
    port: 80
    protocol: TCP
    targetPort: 8080
